version: '3'
services:
  nginx: 
    image: nginx:latest
    container_name: web
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 3000:80

  nodeapp: 
    image: nginxdemos/hello:latest
    container_name: nodeapp