- name: testplaybook
  become: true
  hosts: webservers
  vars:
    # jenkins_hostname: jenkins.jonathan
    # dotnet_package: "dotnet-sdk-3.1"
    # java_packages:
      # - openjdk-8-jdk
    # version: "1.0.0"
    # artifact_dest: "/tmp/coolapp-{{ version }}.tar"
    app_dest: "~/compose"

  roles:
    - role: deploy-compose
      tags: ['deploy']
